### ISSUE TITLE
F.global not being the same 

### ISSUE THREAD

**Issue by TheLordBaski** [totaljs/blogengine#1]
I have this in definitions/settings.js
```
F.global.blogs = ["tutorial", "story"];
F.global.blogstags = ["tutorial"];
F.global.blogslatest = [];
F.global.commentslatest = [];
```
and this in controllers/test.js
```
exports.install = function() {
	F.route("/test", view_test)
};
console.log(F.global); // First one
function view_test(){
	console.log(F.global); //second one
        self.view('test');
}
```

The first one show
```
{ blogs: [ 'tutorial', 'story' ],
  blogstags: [ 'tutorial' ],
  blogslatest: [],
  commentslatest: [] }
```
The second one 
```
{ blogs: [], blogstags: [], blogslatest: [], commentslatest: [] }
```
Do I need to inject F.global somehow or is it the bug ?

**Comment by petersirka** [comment]
Hi @TheLordBaski,
you can't change these values because they are filled from DB. First you have to fill settings:

![Categories](https://cloud.githubusercontent.com/assets/2414252/20456701/d6148eec-ae7b-11e6-8aff-841511580921.png)

---

`F.global.blogs` - is filled automatically here https://github.com/totaljs/blogengine/blob/master/models/blogs.js#L171 from existing blog posts.

`F.global.blogstags` - is filled automtically too https://github.com/totaljs/blogengine/blob/master/models/blogs.js#L177 from existing blog posts.

`F.global.bloglatest` - is same https://github.com/totaljs/blogengine/blob/master/models/blogs.js#L190.

and `F.global.commentslatest` is filled here https://github.com/totaljs/blogengine/blob/master/models/comments.js#L147 (in `comments.js` model)

---

I understand, it can be confusing.
Thank you!

**Comment by TheLordBaski** [comment]
Oh,  I get it.  Thanks.  You can close the issue.
